services:
  - type: web
    name: resume-builder
    env: python
    buildCommand: "pip install -r requirements.txt && python -m flask db upgrade"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: SQLALCHEMY_DATABASE_URI
        sync: false
