"""Add stripe_customer_id field to User model

Revision ID: 168b9bb8f9d4
Revises: 0926e8cc41e0
Create Date: 2025-06-05 16:03:40.664467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168b9bb8f9d4'
down_revision = '0926e8cc41e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
