"""Add structured resume fields for professional summary, skills, work experience, and education

Revision ID: c4ba26db27a2
Revises: 168b9bb8f9d4
Create Date: 2025-06-07 23:10:45.898168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ba26db27a2'
down_revision = '168b9bb8f9d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professional_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('work_experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('additional_sections', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('additional_sections')
        batch_op.drop_column('education')
        batch_op.drop_column('work_experience')
        batch_op.drop_column('skills')
        batch_op.drop_column('professional_summary')

    # ### end Alembic commands ###
